/**
 * Seed 20 demo ideas to Firebase Firestore
 *
 * This script writes 20 fully-populated demo ideas and 5 sample projects
 * to your Firebase project's Firestore database.
 *
 * Usage:
 *   1. Download your Firebase service account key from:
 *      Firebase Console > Project Settings > Service Accounts > Generate new private key
 *      Save it as serviceAccountKey.json in this directory
 *   2. Run: node seedDemoData.js
 */

// If you want to use the client SDK approach instead (no service account needed),
// see the DataContext.jsx auto-seed mechanism which seeds data on first user login.

const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore, Timestamp } = require('firebase-admin/firestore');

let db;

try {
  const serviceAccount = require('./serviceAccountKey.json');
  const app = initializeApp({
    credential: cert(serviceAccount),
  });
  db = getFirestore(app);
} catch (e) {
  console.error('Failed to initialize Firebase Admin SDK.');
  console.error('Make sure serviceAccountKey.json exists in this directory.');
  console.error('Download it from: Firebase Console > Project Settings > Service Accounts');
  console.error(e.message);
  process.exit(1);
}

const demoIdeas = [
  {
    id: 'IDEA-000001',
    applicantName: 'Wong Tsz Kin',
    department: 'IT Innovation Team',
    contactNumber: '9123 4567',
    email: 'wongtz@company.com',
    projectManagerName: 'Chan Mei Ling',
    projectManagerDept: 'IT Department',
    projectManagerEmail: 'cm.ling@company.com',
    projectManagerPhone: '9123 4567',
    ownerName: 'Lee Ka Fai',
    ownerDept: 'Engineering Division',
    ownerContact: '9234 5678',
    ownerEmail: 'lkf@company.com',
    techSupportName: 'Lau Siu Fung',
    techSupportDept: 'IT Department',
    techSupportContact: '9345 6789',
    techSupportEmail: 'lsf@company.com',
    projectType: 'Technology Development',
    title: 'AR-based Site Inspection Tool for Defect Tracking',
    background: 'Current defect tracking relies on manual photography and paperwork, leading to delays and miscommunication between site teams and office.',
    painPoint: 'Defect identification takes 3-5 days on average. We need real-time tracking and digital record keeping.',
    currentWorkarounds: 'Using WhatsApp photos and Excel spreadsheets to manually track defects across sites.',
    projectScope: 'Development of AR mobile app that overlays BIM data on camera view, allowing inspectors to tag defects directly on the 3D model.',
    deliverables: 'Mobile app (iOS/Android), backend API, admin dashboard with analytics, BIM integration module',
    benefits: 'Reduce defect identification time from 3-5 days to same-day resolution, eliminate manual data entry errors',
    projectPhases: 'Phase 1: Core AR features (3 months), Phase 2: BIM integration (2 months), Phase 3: Analytics & reporting (1 month)',
    risks: 'Device compatibility across different phone models, GPS accuracy in indoor construction sites, user adoption resistance',
    expectedStartDate: '2025-09-01',
    targetCompletionDate: '2026-03-31',
    terminationCondition1: 'If defect detection accuracy falls below 85% during pilot testing',
    terminationCondition2: 'If user adoption rate is less than 40% after 3 months',
    terminationCondition3: 'If project cost exceeds budget by more than 30%',
    totalBudget: 1800000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'Hardware: HK$200,000, Software Development: HK$1,000,000, Testing & Deployment: HK$400,000, Training: HK$200,000',
    targetGovFund: 500000,
    targetGovFundDetails: 'ITF - Innovation and Technology Fund (Funding ceiling: 50% of project cost)',
    resourceRequirements: '2x AR developers, 1x UI/UX designer, 1x BIM specialist, Test devices (iPhone, Samsung, Huawei)',
    crossDeptAssistance: 'Engineering Division for BIM data access, Quality Assurance for testing, Site Operations for pilot deployment',
    techDirection: 'Mobile AR using ARKit (iOS) and ARCore (Android) with cloud-based BIM data processing',
    innovationElement: 'First AR-based defect tracking system specifically designed for HK construction industry with offline capability',
    technicalRequirements: 'ARKit 6+, ARCore 1.30+, Node.js v18+, PostgreSQL 15, Redis for caching, Docker for deployment',
    currentStage: 'Feasibility',
    stageStartDate: '2025-09-01',
    stageEndDate: '2025-10-31',
    stageStatus: 'In Progress',
    stageDescription: 'Technical feasibility study and vendor assessment for AR SDK selection',
    requireIP: '待定',
    ipRegion: 'Hong Kong',
    remarks: 'Aligned with company digital transformation roadmap 2025-2026. Potential for patent filing on offline AR processing method.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-01T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000002',
    applicantName: 'Tam Wai Tung',
    department: 'Operations Division',
    contactNumber: '9456 7890',
    email: 'twt@company.com',
    projectManagerName: 'Ng Ka Chun',
    projectManagerDept: 'Engineering Team',
    projectManagerEmail: 'nkc@company.com',
    projectManagerPhone: '9456 7890',
    ownerName: 'Wong Siu Ming',
    ownerDept: 'Operations Division',
    ownerContact: '9567 8901',
    ownerEmail: 'wsm@company.com',
    techSupportName: 'Cheng Ho Yin',
    techSupportDept: 'Engineering Team',
    techSupportContact: '9678 9012',
    techSupportEmail: 'chy@company.com',
    projectType: 'Process Improvement',
    title: 'Carbon Emission Tracking Dashboard for Green Construction',
    background: 'Regulatory requirements for carbon reporting are becoming stricter. Manual data collection is inefficient and error-prone.',
    painPoint: 'No centralized system to track and report carbon emissions across all active construction sites.',
    currentWorkarounds: 'Excel-based manual data collection from each site, compiled monthly by admin staff.',
    projectScope: 'Develop IoT-integrated dashboard that collects and visualizes carbon emission data from all construction sites in real-time.',
    deliverables: 'IoT sensor kits (20 units), real-time data dashboard, automated reporting engine, regulatory compliance module',
    benefits: 'Automated compliance reporting, 30% reduction in manual data collection effort, real-time emission monitoring',
    projectPhases: 'Phase 1: Sensor installation (2 months), Phase 2: Dashboard development (3 months), Phase 3: Reporting engine (1 month)',
    risks: 'Sensor accuracy in outdoor environments, data integration complexity with existing systems, site WiFi connectivity issues',
    expectedStartDate: '2025-10-01',
    targetCompletionDate: '2026-06-30',
    terminationCondition1: 'If data accuracy falls below 90% after calibration',
    terminationCondition2: 'If less than 5 sites are successfully connected within 4 months',
    terminationCondition3: 'If system maintenance cost exceeds HK$50,000/month',
    totalBudget: 2200000,
    fundSource: 'Government Grant',
    budgetBreakdown: 'IoT Sensors: HK$800,000, Software Development: HK$900,000, Installation & Calibration: HK$300,000, Training: HK$200,000',
    targetGovFund: 1100000,
    targetGovFundDetails: 'Green Tech Fund - Carbon Reduction Technology (Up to 50% co-funding)',
    resourceRequirements: 'IoT engineer, full-stack developer, environmental consultant, sensor calibration equipment',
    crossDeptAssistance: 'Site Operations for sensor installation, Safety Team for environmental data validation, IT for server hosting',
    techDirection: 'IoT sensor network using LoRaWAN with cloud-based data aggregation and visualization using Grafana',
    innovationElement: 'Comprehensive IoT monitoring network designed for HK dense urban construction environments with automated EPD compliance reporting',
    technicalRequirements: 'LoRaWAN Gateway, MQTT Broker, TimescaleDB, Grafana, Python data pipeline, Docker, AWS EC2',
    currentStage: 'Idea / R&D',
    stageStartDate: '2025-10-01',
    stageEndDate: '2025-12-31',
    stageStatus: 'Planning',
    stageDescription: 'Research on optimal sensor types and network architecture for construction site conditions',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Supports HK Government 2050碳中和 target. Aligned with EPD environmental monitoring requirements.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'approved',
    aiAnalysis: null,
    createdAt: '2025-06-15T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000003',
    applicantName: 'Lau Hoi Shan',
    department: 'Safety Division',
    contactNumber: '9789 0123',
    email: 'lhs@company.com',
    projectManagerName: 'Chow Man Ho',
    projectManagerDept: 'Safety Team',
    projectManagerEmail: 'cmh@company.com',
    projectManagerPhone: '9789 0123',
    ownerName: 'Tam Wai Tung',
    ownerDept: 'Safety Division',
    ownerContact: '9890 1234',
    ownerEmail: 'twt@company.com',
    techSupportName: 'Kwok Chi Kin',
    techSupportDept: 'Safety Team',
    techSupportContact: '9901 2345',
    techSupportEmail: 'kck@company.com',
    projectType: 'Business Transformation / Development',
    title: 'Smart Helmet with Vital Sign Monitoring for Site Workers',
    background: 'Worker fatigue and heat stress are leading causes of construction site accidents in Hong Kong summer conditions.',
    painPoint: 'No real-time monitoring of worker health conditions. Heat stress incidents are often preventable but undetected.',
    currentWorkarounds: 'Manual temperature checks at site entrance, mandatory water breaks every 2 hours during summer.',
    projectScope: 'Develop smart helmet with temperature, heart rate, and motion sensors with real-time alert system for safety officers.',
    deliverables: 'Smart helmet prototype (50 units), monitoring dashboard, alert system (SMS + dashboard notification)',
    benefits: 'Reduce heat stress incidents by 80%, improve worker safety compliance, early warning for health deterioration',
    projectPhases: 'Phase 1: Hardware prototyping (2 months), Phase 2: Software development (2 months), Phase 3: Pilot testing (2 months)',
    risks: 'Worker acceptance and privacy concerns, battery life in hot conditions, sensor accuracy at high temperature',
    expectedStartDate: '2025-08-01',
    targetCompletionDate: '2026-01-31',
    terminationCondition1: 'If false positive rate exceeds 10% during pilot',
    terminationCondition2: 'If worker refusal rate exceeds 30%',
    terminationCondition3: 'If battery life is less than 8 hours per charge',
    totalBudget: 1500000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'Hardware components: HK$500,000, Shell molding: HK$200,000, Software: HK$500,000, Testing: HK$300,000',
    targetGovFund: 0,
    targetGovFundDetails: '',
    resourceRequirements: 'Hardware engineer, embedded systems developer, industrial designer, safety officer for testing',
    crossDeptAssistance: 'HR for worker communication and consent, IT for cloud infrastructure, Medical team for health data validation',
    techDirection: 'IoT wearable technology with ESP32 microcontroller, BLE connectivity, and TensorFlow Lite for on-device anomaly detection',
    innovationElement: 'First industry-specific smart helmet designed for HK summer construction conditions with integrated heat stress prediction',
    technicalRequirements: 'ESP32-S3, MAX30102 heart rate sensor, DHT22 temperature/humidity, MPU6050 motion sensor, BLE 5.0, LiPo 2000mAh',
    currentStage: 'POC',
    stageStartDate: '2025-08-01',
    stageEndDate: '2025-10-31',
    stageStatus: 'In Progress',
    stageDescription: 'Hardware prototyping and firmware development for sensor integration',
    requireIP: '是',
    ipRegion: 'Hong Kong',
    remarks: 'Potential for Worker Compensation Insurance premium reduction. Patent filing planned for heat stress algorithm.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-10T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000004',
    applicantName: 'Sze Ka Fai',
    department: 'Finance Department',
    contactNumber: '9012 3456',
    email: 'skf@company.com',
    projectManagerName: 'Mak Hoi Tung',
    projectManagerDept: 'Finance Department',
    projectManagerEmail: 'mht@company.com',
    projectManagerPhone: '9012 3456',
    ownerName: 'Chow Man Ho',
    ownerDept: 'Finance Division',
    ownerContact: '9123 4567',
    ownerEmail: 'cmh@company.com',
    techSupportName: 'Liang Wai Kin',
    techSupportDept: 'Finance Department',
    techSupportContact: '9234 5678',
    techSupportEmail: 'lwk@company.com',
    projectType: 'Process Improvement',
    title: 'Automated Invoice Processing System with OCR & Machine Learning',
    background: 'Finance team manually processes 500+ invoices monthly from 200+ subcontractors and suppliers.',
    painPoint: 'Average invoice processing time is 15 days. Payment delays affect supplier relationships and cause project delays.',
    currentWorkarounds: 'Team of 5 clerks manually entering data from paper invoices into ERP system. Double-checking required.',
    projectScope: 'ML-based OCR system that automatically extracts, validates, and routes invoices for approval workflow.',
    deliverables: 'OCR pipeline, validation engine, approval dashboard, ERP integration module (Microsoft Dynamics)',
    benefits: 'Reduce processing time from 15 days to 2 days, eliminate manual data entry errors, enable early payment discounts',
    projectPhases: 'Phase 1: OCR model training on bilingual invoices (2 months), Phase 2: ERP integration (2 months), Phase 3: Testing & rollout (1 month)',
    risks: 'OCR accuracy with Chinese/English mixed documents, ERP API compatibility, data security compliance',
    expectedStartDate: '2025-09-15',
    targetCompletionDate: '2026-02-28',
    terminationCondition1: 'If OCR accuracy is below 85% for Chinese text',
    terminationCondition2: 'If ERP integration causes system instability',
    terminationCondition3: 'If project exceeds HK$1,200,000 budget',
    totalBudget: 900000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'Software Development: HK$500,000, OCR Engine License: HK$150,000, Integration: HK$150,000, Training: HK$100,000',
    targetGovFund: 0,
    targetGovFundDetails: '',
    resourceRequirements: 'ML engineer (OCR specialist), full-stack developer, ERP integration specialist, finance process analyst',
    crossDeptAssistance: 'IT for server hosting and API access, Procurement for supplier data, Legal for document compliance',
    techDirection: 'Computer vision and NLP for document understanding with automated validation rules engine',
    innovationElement: 'Adapted for HK construction industry bilingual (Chinese/English) invoice formats with specialized construction terminology',
    technicalRequirements: 'Python, Tesseract OCR, spaCy NLP, Flask API, React dashboard, Microsoft Dynamics 365 API, PostgreSQL',
    currentStage: 'Feasibility',
    stageStartDate: '2025-09-15',
    stageEndDate: '2025-11-15',
    stageStatus: 'Planning',
    stageDescription: 'Feasibility study on OCR accuracy for mixed Chinese/English construction invoices',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Projected ROI of 300% within first year due to manpower savings of 3 FTE positions.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-05T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000005',
    applicantName: 'Chui Wing Sze',
    department: 'Digital Transformation Division',
    contactNumber: '9345 6789',
    email: 'cws@company.com',
    projectManagerName: 'Tong Ka Chun',
    projectManagerDept: 'IT Department',
    projectManagerEmail: 'tkc@company.com',
    projectManagerPhone: '9345 6789',
    ownerName: 'Ng Ka Chun',
    ownerDept: 'Digital Transformation Division',
    ownerContact: '9456 7890',
    ownerEmail: 'nkc@company.com',
    techSupportName: 'Yu Hoi Ming',
    techSupportDept: 'IT Department',
    techSupportContact: '9567 8901',
    techSupportEmail: 'yhm@company.com',
    projectType: 'Technology Development',
    title: 'Digital Twin Platform for Building Lifecycle Management',
    background: 'Building handover documentation is fragmented across paper, PDFs, and multiple disconnected systems.',
    painPoint: 'Post-handover facility management teams lack comprehensive digital records of building systems and infrastructure.',
    currentWorkarounds: 'Physical O&M manuals stored in site office. Digital copies scattered across shared drives and email attachments.',
    projectScope: 'Create a complete digital twin platform that captures all building data from construction through to facility management.',
    deliverables: 'Digital twin platform, mobile app for facility managers, API for third-party BMS integration, AR viewing module',
    benefits: '50% reduction in facility management issues, centralized building data repository, improved handover efficiency',
    projectPhases: 'Phase 1: Data collection & BIM integration (3 months), Phase 2: Platform development (4 months), Phase 3: Mobile app (2 months)',
    risks: 'Data completeness from subcontractors, platform complexity, user adoption by facility management teams',
    expectedStartDate: '2025-11-01',
    targetCompletionDate: '2026-10-31',
    terminationCondition1: 'If BIM integration fails due to incompatible file formats',
    terminationCondition2: 'If platform performance is below 60fps on target mobile devices',
    terminationCondition3: 'If cost exceeds HK$5,000,000',
    totalBudget: 4500000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'Software Development: HK$2,500,000, BIM Processing Engine: HK$500,000, Mobile App: HK$800,000, Infrastructure: HK$700,000',
    targetGovFund: 1500000,
    targetGovFundDetails: 'CITF - Construction Innovation and Technology Fund (Digital Construction category)',
    resourceRequirements: '3D visualization developers, BIM specialists, backend engineers, UI/UX designer, DevOps engineer',
    crossDeptAssistance: 'Engineering for BIM data, Facility Management for requirements, IT for cloud infrastructure',
    techDirection: 'Cloud-based 3D visualization using WebGL with real-time IoT data integration for facility management',
    innovationElement: 'End-to-end lifecycle digital twin for HK construction-facility management handover process',
    technicalRequirements: 'Autodesk Forge API, Three.js/Unity3D WebGL, Azure Digital Twins, GraphQL, React, Node.js, PostgreSQL',
    currentStage: 'Idea / R&D',
    stageStartDate: '2025-11-01',
    stageEndDate: '2026-01-31',
    stageStatus: 'Planning',
    stageDescription: 'R&D on digital twin architecture and BIM data integration standards',
    requireIP: '待定',
    ipRegion: 'Hong Kong',
    remarks: 'Strategic initiative aligned with HK Smart City Blueprint. Potential for cross-industry application.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'rejected',
    aiAnalysis: null,
    createdAt: '2025-06-01T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000006',
    applicantName: 'Fung Ka Ho',
    department: 'Environmental Team',
    contactNumber: '9222 3344',
    email: 'fkh@company.com',
    projectManagerName: 'Cheung Pui Lam',
    projectManagerDept: 'Environmental Team',
    projectManagerEmail: 'cpl@company.com',
    projectManagerPhone: '9111 2233',
    ownerName: 'Tam Ka Chun',
    ownerDept: 'Sustainability Division',
    ownerContact: '9222 3344',
    ownerEmail: 'tkc@company.com',
    techSupportName: 'Wong Hoi Ming',
    techSupportDept: 'Environmental Team',
    techSupportContact: '9333 4455',
    techSupportEmail: 'whm@company.com',
    projectType: 'Business Transformation / Development',
    title: 'AI-powered Construction Waste Management System',
    background: 'Construction waste accounts for 25% of total landfill volume in Hong Kong. Current waste sorting is manual and inaccurate.',
    painPoint: 'Manual waste sorting is labour-intensive with only 30% recycling rate. No real-time waste tracking across sites.',
    currentWorkarounds: 'Manual sorting at source with color-coded bins. Monthly waste audits by environmental team.',
    projectScope: 'Develop AI-powered waste sorting station with conveyor belt cameras and IoT weight sensors connected to a central analytics dashboard.',
    deliverables: 'AI waste sorting station prototype, IoT weight sensors (10 units), waste analytics dashboard, monthly compliance report generator',
    benefits: 'Increase recycling rate from 30% to 75%, reduce landfill costs by HK$2M annually, automated EPD compliance reporting',
    projectPhases: 'Phase 1: Camera & sensor installation (2 months), Phase 2: AI model training on waste types (3 months), Phase 3: Dashboard & reporting (2 months)',
    risks: 'Waste type diversity across different construction phases, camera accuracy in dusty conditions, sensor calibration drift',
    expectedStartDate: '2025-10-01',
    targetCompletionDate: '2026-06-30',
    terminationCondition1: 'If recycling rate improvement is less than 20%',
    terminationCondition2: 'If system uptime is below 90%',
    terminationCondition3: 'If AI classification accuracy is below 80%',
    totalBudget: 2800000,
    fundSource: 'Government Grant',
    budgetBreakdown: 'Hardware (Cameras, Sensors, Conveyor): HK$1,200,000, AI Software Development: HK$1,000,000, Installation: HK$400,000, Training: HK$200,000',
    targetGovFund: 1400000,
    targetGovFundDetails: 'Green Tech Fund - Waste Reduction Category (50% co-funding available)',
    resourceRequirements: 'Computer vision engineer, mechanical engineer, IoT specialist, environmental consultant',
    crossDeptAssistance: 'Site Operations for installation space, Safety Team for hazard assessment, Procurement for waste contractor coordination',
    techDirection: 'Computer vision with deep learning for real-time waste classification on conveyor belt with automated sorting mechanisms',
    innovationElement: 'First AI-powered construction waste sorting system tailored for HK building material types and EPD reporting standards',
    technicalRequirements: 'TensorFlow, OpenCV, YOLOv8, Raspberry Pi 5, AWS IoT Core, React Dashboard, InfluxDB, MQTT',
    currentStage: 'Feasibility',
    stageStartDate: '2025-10-01',
    stageEndDate: '2025-11-30',
    stageStatus: 'Planning',
    stageDescription: 'Feasibility study on waste types across active sites and AI model training data collection',
    requireIP: '是',
    ipRegion: 'Hong Kong',
    remarks: 'Supports HK Government Waste Blueprint 2035 and circular economy initiatives. Patent potential for AI waste classification.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-14T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000007',
    applicantName: 'Lui Wai Tung',
    department: 'Finance & Contracts',
    contactNumber: '9555 6677',
    email: 'lwt@company.com',
    projectManagerName: 'Shum Ka Fai',
    projectManagerDept: 'Finance & Contracts',
    projectManagerEmail: 'skf@company.com',
    projectManagerPhone: '9444 5566',
    ownerName: 'Tsang Hoi Shan',
    ownerDept: 'Contracts Division',
    ownerContact: '9555 6677',
    ownerEmail: 'ths@company.com',
    techSupportName: 'Ma Chi Ho',
    techSupportDept: 'Finance & Contracts',
    techSupportContact: '9666 7788',
    techSupportEmail: 'mch@company.com',
    projectType: 'Technology Development',
    title: 'Blockchain-based Subcontractor Payment Platform',
    background: 'Subcontractor payment delays are a major pain point in the construction industry, often taking 60-90 days for processing.',
    painPoint: 'Payment disputes and delays damage subcontractor relationships. Manual verification processes are slow and lack transparency.',
    currentWorkarounds: 'Email-based invoice submission, manual verification, cheque issuance. Average 75-day payment cycle.',
    projectScope: 'Build a blockchain-based smart contract platform that automates milestone-based payments to subcontractors.',
    deliverables: 'Smart contract templates, payment processing engine, subcontractor portal, audit trail dashboard, mobile app',
    benefits: 'Reduce payment cycle from 90 days to 7 days, eliminate payment disputes, improve subcontractor trust and retention',
    projectPhases: 'Phase 1: Smart contract development (2 months), Phase 2: Platform development (2 months), Phase 3: Pilot with 5 subcontractors (2 months)',
    risks: 'Subcontractor technology adoption barriers, regulatory compliance with HKMA guidelines, blockchain scalability',
    expectedStartDate: '2025-11-01',
    targetCompletionDate: '2026-08-31',
    terminationCondition1: 'If transaction processing speed is below 100 TPS',
    terminationCondition2: 'If subcontractor adoption rate is below 50% during pilot',
    terminationCondition3: 'If legal compliance issues arise with smart contract enforceability',
    totalBudget: 3200000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'Smart Contract Development: HK$800,000, Platform Development: HK$1,200,000, Security Audit: HK$500,000, Pilot Program: HK$700,000',
    targetGovFund: 1000000,
    targetGovFundDetails: 'ITF - Innovation and Technology Fund (FinTech category)',
    resourceRequirements: 'Blockchain developers (Solidity), full-stack developers, smart contract auditor, legal consultant',
    crossDeptAssistance: 'Legal for contract template review, IT for infrastructure, Procurement for subcontractor onboarding',
    techDirection: 'Permissioned blockchain using Hyperledger Fabric for enterprise-grade security with automated smart contract execution',
    innovationElement: 'First blockchain-based payment platform specifically designed for HK construction subcontractor ecosystem',
    technicalRequirements: 'Hyperledger Fabric, Solidity, Node.js, React, MongoDB, Azure Blockchain Service, Web3.js',
    currentStage: 'Idea / R&D',
    stageStartDate: '2025-11-01',
    stageEndDate: '2026-01-31',
    stageStatus: 'Planning',
    stageDescription: 'R&D on smart contract templates and blockchain architecture for construction payment workflows',
    requireIP: '是',
    ipRegion: 'Hong Kong',
    remarks: 'Potential industry-wide impact - can be scaled to entire HK construction supply chain ecosystem.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-15T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000008',
    applicantName: 'Yung Tsz Ching',
    department: 'Safety Training Team',
    contactNumber: '9888 9900',
    email: 'ytc@company.com',
    projectManagerName: 'Law Hoi Tung',
    projectManagerDept: 'Safety Training',
    projectManagerEmail: 'lht@company.com',
    projectManagerPhone: '9777 8899',
    ownerName: 'Fung Ka Wai',
    ownerDept: 'Safety Division',
    ownerContact: '9888 9900',
    ownerEmail: 'fkw@company.com',
    techSupportName: 'Cheung Wai Lam',
    techSupportDept: 'Safety Training',
    techSupportContact: '9999 0011',
    techSupportEmail: 'cwl@company.com',
    projectType: 'Customer Experience',
    title: 'VR Safety Training Simulator for High-Risk Construction Operations',
    background: 'Traditional safety training relies on classroom sessions and videos, which lack engagement and real-world context.',
    painPoint: 'Workers forget safety protocols because classroom training is abstract. Accident rates remain high for new workers.',
    currentWorkarounds: 'Annual classroom training sessions, safety videos, and on-site toolbox talks. No refresher training between sessions.',
    projectScope: 'Develop VR training modules for the top 10 high-risk construction operations including working at height, confined space, and crane operations.',
    deliverables: '10 VR training modules, instructor dashboard, trainee progress tracking system, VR headset kits (20 units)',
    benefits: 'Reduce workplace accidents by 45%, improve training retention by 70%, standardize safety training across all sites',
    projectPhases: 'Phase 1: Content development with safety experts (3 months), Phase 2: VR module programming (4 months), Phase 3: Pilot training program (2 months)',
    risks: 'Motion sickness in some users, VR hardware maintenance costs, content update frequency for regulatory changes',
    expectedStartDate: '2025-09-01',
    targetCompletionDate: '2026-05-31',
    terminationCondition1: 'If trainee satisfaction score is below 70%',
    terminationCondition2: 'If training effectiveness shows less than 30% improvement in safety knowledge',
    terminationCondition3: 'If VR hardware failure rate exceeds 10% per month',
    totalBudget: 2500000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'VR Headsets (20x Quest 3): HK$800,000, VR Software Development: HK$1,000,000, Content Creation: HK$500,000, Training Materials: HK$200,000',
    targetGovFund: 500000,
    targetGovFundDetails: 'CITF - Safety Training Enhancement Grant',
    resourceRequirements: 'Unity3D developers, 3D modelers, instructional designer, safety trainer consultant',
    crossDeptAssistance: 'Safety Division for scenario design, HR for training scheduling, IT for hardware management',
    techDirection: 'Immersive VR training using Unity3D with realistic physics simulation and interactive scenario-based learning',
    innovationElement: 'Tailored VR training for HK construction industry-specific high-risk operations and LD regulatory requirements',
    technicalRequirements: 'Unity3D 2022 LTS, SteamVR, Oculus SDK, Node.js backend, PostgreSQL, WebSocket for multiplayer training',
    currentStage: 'POC',
    stageStartDate: '2025-09-01',
    stageEndDate: '2025-11-30',
    stageStatus: 'Planning',
    stageDescription: 'Proof of concept developing 2 pilot VR modules (Working at Height + Confined Space)',
    requireIP: '待定',
    ipRegion: 'Hong Kong',
    remarks: 'Can be integrated with mandatory safety training certification requirements. Potential for industry-wide adoption.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-16T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000009',
    applicantName: 'Kwok Man Ho',
    department: 'Quality Control',
    contactNumber: '9112 3456',
    email: 'kmh@company.com',
    projectManagerName: 'Yip Tsz Kin',
    projectManagerDept: 'Quality Control',
    projectManagerEmail: 'ytk@company.com',
    projectManagerPhone: '9001 2345',
    ownerName: 'Chung Wai Sze',
    ownerDept: 'Quality Division',
    ownerContact: '9112 3456',
    ownerEmail: 'cws@company.com',
    techSupportName: 'Lam Hoi Fung',
    techSupportDept: 'Quality Control',
    techSupportContact: '9223 4567',
    techSupportEmail: 'lhf@company.com',
    projectType: 'Technology Development',
    title: 'Automated Concrete Strength Prediction using Machine Learning',
    background: 'Concrete strength testing requires 28 days of curing before results are available, causing project delays.',
    painPoint: 'Waiting 28 days for concrete test results delays construction schedules. Early rejection of poor concrete is impossible.',
    currentWorkarounds: 'Cube testing at 7 days for early indication, but official results still require 28-day wait.',
    projectScope: 'Develop ML model using historical data from 10,000+ concrete samples to predict 28-day strength from 3-day and 7-day test data.',
    deliverables: 'ML prediction model, mobile testing app, cloud-based data collection pipeline, API for ERP integration',
    benefits: 'Reduce waiting time from 28 days to 7 days, save 3 weeks per structural pour, reduce rework costs by 25%',
    projectPhases: 'Phase 1: Historical data collection & cleaning (2 months), Phase 2: Model training & validation (3 months), Phase 3: Mobile app & deployment (2 months)',
    risks: 'Model accuracy variance with different aggregate sources, sensor data quality issues, regulatory acceptance of ML predictions',
    expectedStartDate: '2025-09-15',
    targetCompletionDate: '2026-04-30',
    terminationCondition1: 'If prediction accuracy (R²) is below 0.90',
    terminationCondition2: 'If mean absolute error exceeds 3 MPa',
    terminationCondition3: 'If model fails regulatory validation by HK Housing Authority',
    totalBudget: 1800000,
    fundSource: 'Government Grant',
    budgetBreakdown: 'Data Collection & Cleaning: HK$200,000, ML Development: HK$700,000, Mobile App: HK$500,000, Testing: HK$400,000',
    targetGovFund: 900000,
    targetGovFundDetails: 'ITF - Innovation and Technology Fund (AI/ML Research Category)',
    resourceRequirements: 'ML engineer, data scientist, mobile developer, civil engineering consultant, testing lab access',
    crossDeptAssistance: 'Quality Control for historical data access, Engineering for material property validation, IT for cloud infrastructure',
    techDirection: 'Supervised machine learning using ensemble methods (XGBoost, Random Forest) with feature engineering on concrete mix parameters',
    innovationElement: 'First ML-based concrete strength prediction model trained on HK-specific materials, aggregate types, and environmental conditions',
    technicalRequirements: 'Python, scikit-learn, XGBoost, TensorFlow, Flask API, React Native, AWS SageMaker, PostgreSQL, Docker',
    currentStage: 'Demo',
    stageStartDate: '2025-09-15',
    stageEndDate: '2025-12-31',
    stageStatus: 'Planning',
    stageDescription: 'Initial model development using historical data and proof of concept',
    requireIP: '是',
    ipRegion: 'Hong Kong',
    remarks: 'Potential for industry-wide adoption - can be standardized across all HK construction projects and approved by HKHA.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-12T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000010',
    applicantName: 'Shek Hoi Ming',
    department: 'Environmental Monitoring',
    contactNumber: '9445 6789',
    email: 'shm@company.com',
    projectManagerName: 'Or Ka Chun',
    projectManagerDept: 'Environmental Monitoring',
    projectManagerEmail: 'okc@company.com',
    projectManagerPhone: '9334 5678',
    ownerName: 'Lau Wai Tung',
    ownerDept: 'Environmental Division',
    ownerContact: '9445 6789',
    ownerEmail: 'lwt@company.com',
    techSupportName: 'Choi Wing Sze',
    techSupportDept: 'Environmental Monitoring',
    techSupportContact: '9556 7890',
    techSupportEmail: 'cws@company.com',
    projectType: 'Business Transformation / Development',
    title: 'Smart Noise & Dust Monitoring Network for Construction Sites',
    background: 'Construction sites frequently receive noise complaints from nearby residents. Regulatory fines for exceeding limits are increasing.',
    painPoint: 'Manual noise/dust monitoring is infrequent and reactive. Fines of HK$50,000+ per violation affect project profitability.',
    currentWorkarounds: 'Weekly manual noise readings using handheld meters. Dust monitoring done monthly by external consultant.',
    projectScope: 'Deploy IoT sensor network across active construction sites with real-time monitoring dashboard and automated alert system.',
    deliverables: 'IoT sensor nodes (50 units), cloud monitoring dashboard, automated EPD compliance reports, SMS/email alert system',
    benefits: 'Reduce noise complaints by 60%, eliminate regulatory fines, automated compliance reporting, improve community relations',
    projectPhases: 'Phase 1: Sensor deployment across 5 sites (1 month), Phase 2: Dashboard development (2 months), Phase 3: Alert & reporting system (1 month)',
    risks: 'Sensor accuracy in high-temperature outdoor conditions, network connectivity at basement excavation levels, vandalism',
    expectedStartDate: '2025-10-01',
    targetCompletionDate: '2026-03-31',
    terminationCondition1: 'If sensor accuracy is below 95% after field calibration',
    terminationCondition2: 'If network uptime is below 99%',
    terminationCondition3: 'If false alert rate exceeds 5%',
    totalBudget: 1600000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'IoT Sensors (50 units): HK$800,000, Dashboard Development: HK$400,000, Installation: HK$200,000, Maintenance (1 year): HK$200,000',
    targetGovFund: 800000,
    targetGovFundDetails: 'Green Tech Fund - Environmental Monitoring Category',
    resourceRequirements: 'IoT engineer, full-stack developer, environmental specialist, site installation team',
    crossDeptAssistance: 'Site Operations for sensor placement, Safety Team for compliance monitoring, IT for cloud hosting',
    techDirection: 'LoRaWAN-based IoT sensor network with edge computing for real-time noise/dust analysis and automated alerts',
    innovationElement: 'Comprehensive IoT monitoring network designed for HK dense urban construction environment with EPD integration',
    technicalRequirements: 'LoRaWAN, MQTT, Grafana, TimescaleDB, Python data pipeline, ThingsBoard, Docker, AWS EC2',
    currentStage: 'Feasibility',
    stageStartDate: '2025-10-01',
    stageEndDate: '2025-11-30',
    stageStatus: 'Planning',
    stageDescription: 'Site survey and sensor placement planning across active construction sites',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Aligns with EPD noise monitoring requirements and HK Air Quality Objectives. Potential for government co-funding.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-13T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000011',
    applicantName: 'Chiu Ka Fai',
    department: 'Safety Operations',
    contactNumber: '9778 9012',
    email: 'ckf@company.com',
    projectManagerName: 'Leung Hoi Shan',
    projectManagerDept: 'Safety Operations',
    projectManagerEmail: 'lhs@company.com',
    projectManagerPhone: '9667 8901',
    ownerName: 'Kwok Tsz Kin',
    ownerDept: 'Operations Division',
    ownerContact: '9778 9012',
    ownerEmail: 'ktk@company.com',
    techSupportName: 'Yuen Man Wai',
    techSupportDept: 'Safety Operations',
    techSupportContact: '9889 0123',
    techSupportEmail: 'ymw@company.com',
    projectType: 'Process Improvement',
    title: 'Digital Permit-to-Work System for Construction Sites',
    background: 'Permit-to-work (PTW) process is entirely paper-based. Permits take 2-3 days to process and are often lost or damaged.',
    painPoint: 'Paper permits are inefficient - average processing time is 48 hours. Lost permits cause work stoppages and safety risks.',
    currentWorkarounds: 'Carbon copy paper forms, manual delivery to safety office, physical approval signatures required.',
    projectScope: 'Develop a digital PTW system with mobile app for site supervisors, automated approval workflows, and real-time permit tracking.',
    deliverables: 'Mobile app (iOS/Android), web dashboard, automated approval engine, digital signature integration, complete audit trail',
    benefits: 'Reduce permit processing time from 48 hours to 2 hours, eliminate lost permits, improve safety compliance tracking by 90%',
    projectPhases: 'Phase 1: Workflow design & app development (3 months), Phase 2: Digital signature integration (1 month), Phase 3: Pilot & rollout (2 months)',
    risks: 'User adoption by older workforce, digital signature legal compliance under HK law, offline mode reliability at remote sites',
    expectedStartDate: '2025-10-15',
    targetCompletionDate: '2026-04-30',
    terminationCondition1: 'If permit processing time reduction is less than 50%',
    terminationCondition2: 'If user adoption rate is below 60% after 3 months',
    terminationCondition3: 'If system is non-compliant with LD safety management requirements',
    totalBudget: 1200000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'Mobile App Development: HK$600,000, Backend Development: HK$300,000, Digital Signature License: HK$100,000, Training: HK$200,000',
    targetGovFund: 0,
    targetGovFundDetails: '',
    resourceRequirements: 'React Native developer, backend developer, DevOps engineer, safety process consultant',
    crossDeptAssistance: 'Safety Division for workflow design, IT for integration with existing systems, Legal for digital signature compliance',
    techDirection: 'Cross-platform mobile app with offline-first architecture and digital signature integration for legal compliance',
    innovationElement: 'First comprehensive digital PTW system tailored for HK construction industry safety requirements and LD inspection standards',
    technicalRequirements: 'React Native, Node.js, PostgreSQL, DocuSign API, Redis cache, Docker, Kubernetes for deployment',
    currentStage: 'Pilot',
    stageStartDate: '2025-10-15',
    stageEndDate: '2026-01-31',
    stageStatus: 'Planning',
    stageDescription: 'Initial development and pilot deployment on 3 construction sites',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Supports LD safety management system requirements and ISO 45001 certification. Paperless initiative.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-17T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000012',
    applicantName: 'Pang Wai Lun',
    department: 'Site Safety',
    contactNumber: '9001 2345',
    email: 'pwl@company.com',
    projectManagerName: 'Lok Ka Chun',
    projectManagerDept: 'Site Safety',
    projectManagerEmail: 'lkc@company.com',
    projectManagerPhone: '9990 1234',
    ownerName: 'Yip Siu Ming',
    ownerDept: 'Safety Division',
    ownerContact: '9001 2345',
    ownerEmail: 'ysm@company.com',
    techSupportName: 'Fu Hoi Ming',
    techSupportDept: 'Site Safety',
    techSupportContact: '9112 3456',
    techSupportEmail: 'fhm@company.com',
    projectType: 'Technology Development',
    title: 'Computer Vision System for PPE Compliance Detection',
    background: 'PPE violations are the leading cause of reportable injuries. Manual safety inspections cover only 10% of work hours.',
    painPoint: 'Safety officers cannot monitor all workers at all times. PPE violations go undetected until accidents happen.',
    currentWorkarounds: 'Random spot checks by safety officers, paper-based violation recording, monthly safety audits.',
    projectScope: 'Deploy AI-powered CCTV system that analyzes video feeds in real-time to detect hard hats, safety vests, gloves, harnesses, and safety glasses.',
    deliverables: 'AI detection engine, CCTV integration module (8 cameras per site), real-time alert dashboard, monthly compliance reports',
    benefits: 'Increase PPE compliance from 75% to 98%, reduce reportable injuries by 50%, automated 24/7 safety monitoring',
    projectPhases: 'Phase 1: AI model training on construction site data (3 months), Phase 2: CCTV system integration (2 months), Phase 3: Dashboard & pilot (2 months)',
    risks: 'Camera coverage blind spots, false positives in poor lighting conditions, worker privacy concerns, data protection compliance',
    expectedStartDate: '2025-09-01',
    targetCompletionDate: '2026-04-30',
    terminationCondition1: 'If detection accuracy is below 90% for any PPE type',
    terminationCondition2: 'If false positive rate exceeds 5%',
    terminationCondition3: 'If worker privacy complaints result in work stoppage',
    totalBudget: 2100000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'AI Model Development: HK$700,000, CCTV Hardware (40 cameras): HK$600,000, Integration: HK$500,000, Installation: HK$300,000',
    targetGovFund: 700000,
    targetGovFundDetails: 'CITF - Safety Technology Enhancement Grant',
    resourceRequirements: 'Computer vision engineer, AI/ML specialist, CCTV technician, safety officer for validation',
    crossDeptAssistance: 'Safety Division for compliance requirements, IT for network infrastructure, Legal for privacy compliance',
    techDirection: 'Edge AI processing using NVIDIA Jetson with YOLOv8 for real-time PPE detection without cloud dependency',
    innovationElement: 'PPE detection model specifically trained for HK construction site conditions (heat, dust, mixed lighting, multiple PPE types)',
    technicalRequirements: 'YOLOv8, OpenCV, NVIDIA Jetson Orin, Python Flask, React dashboard, Redis, InfluxDB, RTSP camera feeds',
    currentStage: 'Demo',
    stageStartDate: '2025-09-01',
    stageEndDate: '2025-12-31',
    stageStatus: 'Planning',
    stageDescription: 'AI model development and training using site CCTV footage',
    requireIP: '是',
    ipRegion: 'Hong Kong',
    remarks: 'Can be integrated with existing site CCTV infrastructure. Potential insurance premium reduction from insurers.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-18T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000013',
    applicantName: 'Tse Hoi Tung',
    department: 'Surveying Team',
    contactNumber: '9334 5678',
    email: 'tht@company.com',
    projectManagerName: 'Kam Ka Wai',
    projectManagerDept: 'Surveying Team',
    projectManagerEmail: 'kkw@company.com',
    projectManagerPhone: '9223 4567',
    ownerName: 'Lui Man Ho',
    ownerDept: 'Surveying Division',
    ownerContact: '9334 5678',
    ownerEmail: 'lmh@company.com',
    techSupportName: 'Shing Chi Kin',
    techSupportDept: 'Surveying Team',
    techSupportContact: '9445 6789',
    techSupportEmail: 'sck@company.com',
    projectType: 'Technology Development',
    title: 'Drone-based Topographical Survey Automation System',
    background: 'Traditional topographical surveys take 2-3 weeks and require significant manual field work and equipment setup.',
    painPoint: 'Survey delays impact project planning and design timelines. Manual surveying is expensive and weather-dependent.',
    currentWorkarounds: 'Hired external surveyors with total stations. Manual data processing and CAD drafting.',
    projectScope: 'Implement drone-based surveying system with automated flight paths, real-time photogrammetry, and AI-powered terrain analysis.',
    deliverables: 'Drone fleet (3x DJI Matrice), automated flight planning software, 3D mapping engine, terrain analysis dashboard, survey report generator',
    benefits: 'Reduce survey time from 3 weeks to 2 days, cut surveying costs by 60%, enable weekly site progress tracking with orthophotos',
    projectPhases: 'Phase 1: Drone procurement & pilot training (1 month), Phase 2: Software development (3 months), Phase 3: Integration & testing (2 months)',
    risks: 'Civil Aviation Department regulations for drone flights, weather dependency, large data processing volume, pilot certification requirements',
    expectedStartDate: '2025-10-01',
    targetCompletionDate: '2026-05-31',
    terminationCondition1: 'If survey accuracy exceeds 5cm RMSE',
    terminationCondition2: 'If flight success rate is below 85% due to weather',
    terminationCondition3: 'If CADD integration fails',
    totalBudget: 3500000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'Drones (3x DJI Matrice 350): HK$1,200,000, Photogrammetry Software: HK$500,000, Development: HK$800,000, Training: HK$500,000, Maintenance: HK$500,000',
    targetGovFund: 1000000,
    targetGovFundDetails: 'CITF - Construction Innovation Fund (Surveying Technology Category)',
    resourceRequirements: 'Licensed drone pilot, photogrammetry specialist, full-stack developer, GIS analyst',
    crossDeptAssistance: 'CADD Department for AutoCAD integration, Engineering for survey requirements, Safety Team for flight risk assessment',
    techDirection: 'Automated drone photogrammetry with real-time 3D point cloud generation and AI-powered terrain classification',
    innovationElement: "Integrated drone surveying solution designed for HK's complex topography and dense urban construction environment",
    technicalRequirements: 'DJI Pilot SDK, Pix4D Mapper, Python, CesiumJS 3D visualization, AWS S3 storage, WebODM, React dashboard, PostgreSQL with PostGIS',
    currentStage: 'Feasibility',
    stageStartDate: '2025-10-01',
    stageEndDate: '2025-12-31',
    stageStatus: 'Planning',
    stageDescription: 'Regulatory compliance review and pilot training program initiation',
    requireIP: '待定',
    ipRegion: 'Hong Kong',
    remarks: 'Aligned with HK Smart City initiative for digital terrain mapping. CADD department already expressed strong interest.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-16T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000014',
    applicantName: 'Fok Tsz Ming',
    department: 'Equipment Management',
    contactNumber: '9667 8901',
    email: 'ftm@company.com',
    projectManagerName: 'Chun Hoi Shan',
    projectManagerDept: 'Equipment Management',
    projectManagerEmail: 'chs@company.com',
    projectManagerPhone: '9556 7890',
    ownerName: 'Sze Ka Lok',
    ownerDept: 'Equipment Division',
    ownerContact: '9667 8901',
    ownerEmail: 'skl@company.com',
    techSupportName: 'Liu Wai Sze',
    techSupportDept: 'Equipment Management',
    techSupportContact: '9778 9012',
    techSupportEmail: 'lws@company.com',
    projectType: 'Business Transformation / Development',
    title: 'IoT-enabled Smart Tower Crane Monitoring System',
    background: 'Tower crane accidents are catastrophic. Current safety checks are manual and periodic, missing early warning signs.',
    painPoint: 'Crane operators lack real-time load and structural health data. Maintenance is reactive, leading to costly downtime.',
    currentWorkarounds: 'Daily visual inspections by crane operators. Monthly maintenance by external engineers.',
    projectScope: 'Install IoT sensors on tower cranes to monitor load weight, wind speed, structural vibration, and temperature in real-time.',
    deliverables: 'IoT sensor kit per crane (strain gauges, anemometer, accelerometer), operator display unit, central monitoring dashboard, predictive maintenance engine',
    benefits: 'Eliminate crane overload accidents, reduce unplanned downtime by 70%, extend crane lifespan through predictive maintenance',
    projectPhases: 'Phase 1: Sensor hardware development (3 months), Phase 2: Software & dashboard (2 months), Phase 3: Installation & testing on 5 cranes (2 months)',
    risks: 'Sensor durability in harsh outdoor conditions, wireless interference on congested sites, operator training, sensor calibration drift',
    expectedStartDate: '2025-11-01',
    targetCompletionDate: '2026-07-31',
    terminationCondition1: 'If sensor reliability is below 99%',
    terminationCondition2: 'If false alert rate exceeds 10%',
    terminationCondition3: 'If predictive maintenance accuracy is below 80%',
    totalBudget: 3000000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'Sensor Hardware (5 kits): HK$1,500,000, Software Development: HK$800,000, Installation: HK$400,000, Calibration: HK$300,000',
    targetGovFund: 1500000,
    targetGovFundDetails: 'CITF - Safety Innovation Fund (Crane Safety Category)',
    resourceRequirements: 'Embedded systems engineer, mechanical engineer, IoT specialist, full-stack developer, crane technician',
    crossDeptAssistance: 'Equipment Division for crane access, Safety Team for risk assessment, Insurance for premium negotiation',
    techDirection: 'Industrial IoT with edge computing for real-time structural health monitoring and ML-based predictive maintenance',
    innovationElement: 'First comprehensive IoT crane monitoring system designed for HK high-density construction sites with multiple cranes in close proximity',
    technicalRequirements: 'ESP32, LoRaWAN, MQTT, TensorFlow (predictive maintenance), Grafana dashboards, Node.js, TimescaleDB, AWS IoT Core',
    currentStage: 'Idea / R&D',
    stageStartDate: '2025-11-01',
    stageEndDate: '2026-01-31',
    stageStatus: 'Planning',
    stageDescription: 'Research on optimal sensor types and crane structural analysis',
    requireIP: '是',
    ipRegion: 'Hong Kong',
    remarks: 'Potential for insurance premium reduction. Supports LD crane safety inspection requirements under CAP 59M.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-19T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000015',
    applicantName: 'Chu Wing Ka',
    department: 'Project Controls',
    contactNumber: '9990 1234',
    email: 'cwk@company.com',
    projectManagerName: 'Wan Chi Ho',
    projectManagerDept: 'Project Controls',
    projectManagerEmail: 'wch@company.com',
    projectManagerPhone: '9889 0123',
    ownerName: 'Law Pui Shan',
    ownerDept: 'Project Controls Division',
    ownerContact: '9990 1234',
    ownerEmail: 'lps@company.com',
    techSupportName: 'Ko Hoi Ming',
    techSupportDept: 'Project Controls',
    techSupportContact: '9001 2345',
    techSupportEmail: 'khm@company.com',
    projectType: 'Technology Development',
    title: 'Automated Progress Photo Analysis & Timeline Generation',
    background: 'Progress tracking relies on manual photo taking and comparison. Weekly reports take 2-3 days to compile.',
    painPoint: 'Project managers spend 20% of their time on progress photo management. Inconsistent photo quality causes disputes.',
    currentWorkarounds: 'Site supervisors take photos with phones, manually organize by date, project managers compile reports in PowerPoint.',
    projectScope: 'Develop AI system that compares site photos against BIM models to automatically detect progress, generate timeline updates, and create visual reports.',
    deliverables: 'Mobile photo capture app with positioning, AI comparison engine, BIM integration module, automated report generator, progress dashboard',
    benefits: 'Reduce reporting time by 80%, provide objective progress evidence, early detection of schedule slippage, eliminate photo disputes',
    projectPhases: 'Phase 1: AI model development for progress detection (3 months), Phase 2: Mobile app and backend (2 months), Phase 3: BIM integration (2 months)',
    risks: 'BIM model availability across all projects, photo quality variance, viewpoint consistency, model accuracy in complex interior areas',
    expectedStartDate: '2025-09-01',
    targetCompletionDate: '2026-03-31',
    terminationCondition1: 'If progress detection accuracy is below 85%',
    terminationCondition2: 'If report generation takes more than 30 minutes',
    terminationCondition3: 'If BIM integration fails for more than 30% of projects',
    totalBudget: 2000000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'AI Development: HK$800,000, Mobile App: HK$400,000, BIM Integration: HK$400,000, Infrastructure: HK$400,000',
    targetGovFund: 600000,
    targetGovFundDetails: 'CITF - Digital Construction Grant',
    resourceRequirements: 'Computer vision engineer, full-stack developer, BIM specialist, mobile developer',
    crossDeptAssistance: 'Engineering for BIM data, IT for cloud infrastructure, all site teams for photo collection',
    techDirection: 'AI-powered comparison between site photos and BIM models using structure-from-motion and semantic segmentation',
    innovationElement: 'AI-powered progress tracking system designed for HK construction progress reporting standards and employer requirements',
    technicalRequirements: 'PyTorch, OpenCV, Autodesk Forge API, React Native, Node.js, MongoDB, AWS Rekognition, Docker',
    currentStage: 'Demo',
    stageStartDate: '2025-09-01',
    stageEndDate: '2025-12-31',
    stageStatus: 'Planning',
    stageDescription: 'AI model prototype development and testing with sample site photos',
    requireIP: '待定',
    ipRegion: 'Hong Kong',
    remarks: 'Integrates with existing BIM processes. Projected ROI of 400% through time savings across all projects.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-20T00:00:00.000Z',
    uid: 'system',
  },
  // === Ideas 16-20 (new) ===
  {
    id: 'IDEA-000016',
    applicantName: 'Yan Tsz Ching',
    department: 'Procurement Division',
    contactNumber: '9123 9876',
    email: 'ytc@company.com',
    projectManagerName: 'Fung Ka Wai',
    projectManagerDept: 'Procurement',
    projectManagerEmail: 'fkw@company.com',
    projectManagerPhone: '9234 8765',
    ownerName: 'Tse Man Ho',
    ownerDept: 'Procurement Division',
    ownerContact: '9345 7654',
    ownerEmail: 'tmh@company.com',
    techSupportName: 'Lok Hoi Shan',
    techSupportDept: 'Procurement',
    techSupportContact: '9456 6543',
    techSupportEmail: 'lhs@company.com',
    projectType: 'Process Improvement',
    title: 'AI-based Supplier Performance Management Platform',
    background: 'Supplier evaluation is currently done annually using manual spreadsheets with subjective scoring.',
    painPoint: 'No real-time supplier performance data. Poor performing suppliers are not identified until contract renewal.',
    currentWorkarounds: 'Annual supplier evaluation form, manual scoring in Excel, procurement manager subjective assessment.',
    projectScope: 'Develop an AI-powered platform that automatically tracks supplier performance metrics including delivery time, quality, safety, and pricing.',
    deliverables: 'Supplier portal, automated KPI tracking engine, performance dashboard, supplier scorecard generator, alert system',
    benefits: 'Real-time supplier performance visibility, 40% reduction in supplier-related issues, data-driven procurement decisions',
    projectPhases: 'Phase 1: KPI definition & data integration (2 months), Phase 2: Platform development (3 months), Phase 3: Supplier onboarding (2 months)',
    risks: 'Supplier data accuracy, resistance to transparent evaluation, integration with existing ERP, supplier relationship impact',
    expectedStartDate: '2025-11-15',
    targetCompletionDate: '2026-07-31',
    terminationCondition1: 'If less than 50% of suppliers participate in evaluation',
    terminationCondition2: 'If KPI data collection automation is below 70%',
    terminationCondition3: 'If project exceeds HK$1,500,000',
    totalBudget: 1100000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'Platform Development: HK$600,000, Data Integration: HK$200,000, Supplier Portal: HK$200,000, Training: HK$100,000',
    targetGovFund: 0,
    targetGovFundDetails: '',
    resourceRequirements: 'Full-stack developer, data analyst, procurement process consultant',
    crossDeptAssistance: 'Procurement for KPI definition, IT for ERP integration, Legal for supplier data privacy',
    techDirection: 'Cloud-based platform with automated data collection from ERP and external sources with ML-powered supplier risk prediction',
    innovationElement: 'First AI-driven supplier management platform specifically designed for HK construction procurement ecosystem',
    technicalRequirements: 'React, Node.js, PostgreSQL, Python ML pipeline, Microsoft Dynamics API, Docker, AWS',
    currentStage: 'Idea / R&D',
    stageStartDate: '2025-11-15',
    stageEndDate: '2026-01-31',
    stageStatus: 'Planning',
    stageDescription: 'KPI definition workshops with procurement team and initial data audit',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Strategic procurement transformation initiative. Potential for group-wide adoption across all construction divisions.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-21T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000017',
    applicantName: 'Liang Ka Ho',
    department: 'Civil Engineering Team',
    contactNumber: '9567 8901',
    email: 'lkh@company.com',
    projectManagerName: 'Wong Sze Wan',
    projectManagerDept: 'Civil Engineering',
    projectManagerEmail: 'wsw@company.com',
    projectManagerPhone: '9678 9012',
    ownerName: 'Chu Hoi Ming',
    ownerDept: 'Civil Engineering Division',
    ownerContact: '9789 0123',
    ownerEmail: 'chm@company.com',
    techSupportName: 'Ma Tsz Kin',
    techSupportDept: 'Civil Engineering',
    techSupportContact: '9890 1234',
    techSupportEmail: 'mtk@company.com',
    projectType: 'Technology Development',
    title: 'Real-time Structural Health Monitoring System for Excavation Works',
    background: 'Deep excavation works for basements carry significant risks of ground settlement and structural failure.',
    painPoint: 'Structural monitoring data is collected manually weekly. Delayed detection of critical movements risks catastrophic failure.',
    currentWorkarounds: 'Manual inclinometer and settlement marker readings by surveyors. Data compiled in Excel with 3-day delay.',
    projectScope: 'Deploy automated sensor network with real-time monitoring of ground settlement, lateral movement, water pressure, and vibration.',
    deliverables: 'Automated sensor network (inclinometers, piezometers, tilt meters), real-time dashboard, SMS alert system, weekly automated reports',
    benefits: 'Real-time detection of structural movements, prevent catastrophic failures, reduce monitoring costs by 50%, automated compliance records',
    projectPhases: 'Phase 1: Sensor procurement & installation (2 months), Phase 2: Data pipeline & dashboard (2 months), Phase 3: Alert system & testing (1 month)',
    risks: 'Sensor damage during excavation, cable cuts by excavators, data transmission reliability, sensor calibration drift',
    expectedStartDate: '2025-12-01',
    targetCompletionDate: '2026-06-30',
    terminationCondition1: 'If sensor data transmission uptime is below 95%',
    terminationCondition2: 'If monitoring accuracy is below required BD standards',
    terminationCondition3: 'If system fails to detect settlement within 2mm accuracy',
    totalBudget: 1900000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'Sensor Hardware: HK$1,000,000, Data Logger & Gateway: HK$300,000, Software: HK$400,000, Installation: HK$200,000',
    targetGovFund: 950000,
    targetGovFundDetails: 'CITF - Construction Safety Innovation Fund',
    resourceRequirements: 'Geotechnical engineer, IoT engineer, civil structural engineer, site installation team',
    crossDeptAssistance: 'Engineering for structural analysis, Safety Team for emergency response planning, IT for data hosting',
    techDirection: 'Automated sensor network with cellular data transmission and cloud-based real-time analytics with threshold-based alerts',
    innovationElement: 'Comprehensive real-time structural monitoring system for HK deep excavation works with BD compliance reporting',
    technicalRequirements: 'Geotechnical sensors (inclinometers, piezometers), cellular DTU, MQTT, Python, TimescaleDB, Grafana, SMS gateway API',
    currentStage: 'Feasibility',
    stageStartDate: '2025-12-01',
    stageEndDate: '2026-01-31',
    stageStatus: 'Planning',
    stageDescription: 'Site assessment and sensor placement design for upcoming excavation works',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Critical for deep excavation safety compliance. BD requirements mandate continuous monitoring for excavations >5m depth.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-22T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000018',
    applicantName: 'Or Ka Man',
    department: 'IT Department',
    contactNumber: '9001 1111',
    email: 'okm@company.com',
    projectManagerName: 'Tsui Ka Wai',
    projectManagerDept: 'IT Department',
    projectManagerEmail: 'tkw@company.com',
    projectManagerPhone: '9112 2222',
    ownerName: 'Ma Hoi Shan',
    ownerDept: 'Digital Transformation Division',
    ownerContact: '9223 3333',
    ownerEmail: 'mhs@company.com',
    techSupportName: 'Lau Chi Ho',
    techSupportDept: 'IT Department',
    techSupportContact: '9334 4444',
    techSupportEmail: 'lch@company.com',
    projectType: 'Business Transformation / Development',
    title: 'Enterprise-wide Document Management & Collaboration Platform',
    background: 'Project documentation is scattered across shared drives, email attachments, and physical filing cabinets.',
    painPoint: 'Engineers spend 25% of their time searching for documents. Version control is non-existent.',
    currentWorkarounds: 'Network shared drives with folder hierarchy. Document naming conventions inconsistently followed.',
    projectScope: 'Implement a cloud-based document management system with version control, workflow automation, and AI-powered search.',
    deliverables: 'Document management platform, mobile app for site access, automated workflow engine, AI search, integration with BIM 360',
    benefits: 'Reduce document search time by 80%, eliminate version confusion, enable remote document access from any device',
    projectPhases: 'Phase 1: Platform selection & configuration (2 months), Phase 2: Migration from shared drives (3 months), Phase 3: Integration & training (2 months)',
    risks: 'User adoption resistance, data migration complexity, integration with legacy systems, cloud security compliance',
    expectedStartDate: '2025-10-01',
    targetCompletionDate: '2026-05-31',
    terminationCondition1: 'If user adoption is below 70% after 3 months',
    terminationCondition2: 'If data migration fails for more than 5% of documents',
    terminationCondition3: 'If system performance exceeds 2-second response time',
    totalBudget: 2800000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'Platform License (3 years): HK$1,200,000, Migration Services: HK$600,000, Custom Development: HK$600,000, Training: HK$400,000',
    targetGovFund: 0,
    targetGovFundDetails: '',
    resourceRequirements: 'Document management specialist, system integrator, migration team, change management consultant',
    crossDeptAssistance: 'All departments for document tagging, Legal for document retention policy, IT for infrastructure',
    techDirection: 'Cloud-based enterprise document management with AI-powered semantic search and automated metadata extraction',
    innovationElement: 'Comprehensive document management transformation for HK construction company with BIM 360 integration',
    technicalRequirements: 'SharePoint Online or equivalent, Azure Cognitive Search, Microsoft 365 integration, Power Automate workflows',
    currentStage: 'Feasibility',
    stageStartDate: '2025-10-01',
    stageEndDate: '2025-11-30',
    stageStatus: 'Planning',
    stageDescription: 'Requirements gathering and vendor evaluation for document management platform',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Foundation for broader digital transformation. Estimated 300% productivity improvement across all departments.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-22T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000019',
    applicantName: 'Cheung Wai Sze',
    department: 'Quality Assurance',
    contactNumber: '9444 5555',
    email: 'cws@company.com',
    projectManagerName: 'Yip Ka Chun',
    projectManagerDept: 'Quality Assurance',
    projectManagerEmail: 'ykc@company.com',
    projectManagerPhone: '9555 6666',
    ownerName: 'Lau Hoi Tung',
    ownerDept: 'Quality Division',
    ownerContact: '9666 7777',
    ownerEmail: 'lht@company.com',
    techSupportName: 'Tsang Man Ho',
    techSupportDept: 'Quality Assurance',
    techSupportContact: '9777 8888',
    techSupportEmail: 'tmh@company.com',
    projectType: 'Cost Saving',
    title: 'Automated QA Inspection Scheduling & Reporting System',
    background: 'QA inspections are scheduled manually via email and phone calls. Inspection reports take 2-3 days to finalize.',
    painPoint: 'Manual scheduling causes inefficiencies. Delayed inspection reports hold up project milestones and payments.',
    currentWorkarounds: 'Email-based scheduling, paper inspection forms, photos attached to email reports.',
    projectScope: 'Develop automated scheduling and reporting system for QA inspections with mobile data collection and real-time reporting.',
    deliverables: 'Mobile inspection app, automated scheduling engine, digital inspection forms library, real-time report generation, dashboard',
    benefits: 'Reduce inspection scheduling time by 60%, generate reports in real-time, eliminate paper forms, improve inspection compliance',
    projectPhases: 'Phase 1: Digital form development (2 months), Phase 2: Mobile app & scheduling engine (3 months), Phase 3: Dashboard & integration (1 month)',
    risks: 'Inspection form complexity, network connectivity at remote sites, inspector technology adoption, data standardization',
    expectedStartDate: '2025-09-01',
    targetCompletionDate: '2026-02-28',
    terminationCondition1: 'If report generation takes more than 5 minutes',
    terminationCondition2: 'If inspector adoption rate is below 60%',
    terminationCondition3: 'If system cannot operate offline',
    totalBudget: 800000,
    fundSource: 'Department Budget',
    budgetBreakdown: 'Mobile App Development: HK$400,000, Backend Development: HK$250,000, Integration: HK$100,000, Training: HK$50,000',
    targetGovFund: 0,
    targetGovFundDetails: '',
    resourceRequirements: 'Mobile developer, backend developer, QA process consultant, UI/UX designer',
    crossDeptAssistance: 'Quality Division for form design, IT for hosting, all project teams for scheduling coordination',
    techDirection: 'Offline-first mobile app with synchronized data collection and automated report generation engine',
    innovationElement: 'Digital QA inspection system tailored for HK construction quality standards and BS EN ISO 9001 compliance',
    technicalRequirements: 'React Native, Node.js, PostgreSQL, Redis offline queue, PDF generation engine, Docker',
    currentStage: 'POC',
    stageStartDate: '2025-09-01',
    stageEndDate: '2025-11-30',
    stageStatus: 'Planning',
    stageDescription: 'Mobile app prototype development with 5 digital inspection forms',
    requireIP: '否',
    ipRegion: 'Hong Kong',
    remarks: 'Quick win project with low investment and high ROI. Can be expanded to subcontractor QA management in Phase 2.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-23T00:00:00.000Z',
    uid: 'system',
  },
  {
    id: 'IDEA-000020',
    applicantName: 'Ko Chi Kin',
    department: 'Logistics & Supply Chain',
    contactNumber: '9888 9999',
    email: 'kck@company.com',
    projectManagerName: 'Lui Ka Wai',
    projectManagerDept: 'Logistics',
    projectManagerEmail: 'lkw@company.com',
    projectManagerPhone: '9777 8888',
    ownerName: 'Chung Hoi Tung',
    ownerDept: 'Logistics Division',
    ownerContact: '9666 7777',
    ownerEmail: 'cht@company.com',
    techSupportName: 'Shing Ka Fai',
    techSupportDept: 'Logistics',
    techSupportContact: '9555 6666',
    techSupportEmail: 'skf@company.com',
    projectType: 'Cost Saving',
    title: 'Real-time Material Tracking & Inventory Management System',
    background: 'Construction materials are often lost, stolen, or wasted due to poor tracking and inventory management.',
    painPoint: 'Material over-ordering and waste account for 8-10% of project costs. No real-time inventory visibility.',
    currentWorkarounds: 'Manual material logging at site entrance. Weekly stock counts. Excel-based inventory tracking.',
    projectScope: 'Implement RFID/IoT-based material tracking system with real-time inventory management and automated reordering.',
    deliverables: 'RFID tagging system, IoT gate sensors, inventory management dashboard, automated reordering engine, supplier portal',
    benefits: 'Reduce material waste by 40%, eliminate stockouts, prevent material theft, optimize inventory levels across all sites',
    projectPhases: 'Phase 1: RFID infrastructure installation (2 months), Phase 2: Inventory management system (3 months), Phase 3: Reordering engine & supplier integration (2 months)',
    risks: 'RFID read range in metal-rich environment, tag durability, supplier system integration, initial tagging effort for existing stock',
    expectedStartDate: '2025-12-01',
    targetCompletionDate: '2026-08-31',
    terminationCondition1: 'If RFID read accuracy is below 95%',
    terminationCondition2: 'If inventory accuracy improvement is less than 30%',
    terminationCondition3: 'If ROI is not achieved within 18 months',
    totalBudget: 2600000,
    fundSource: 'Company Central Fund',
    budgetBreakdown: 'RFID Hardware & Installation: HK$1,200,000, Software Development: HK$900,000, Integration: HK$300,000, Training: HK$200,000',
    targetGovFund: 800000,
    targetGovFundDetails: 'CITF - Construction Innovation Fund (Logistics Technology)',
    resourceRequirements: 'IoT engineer, full-stack developer, supply chain consultant, RFID specialist',
    crossDeptAssistance: 'Procurement for supplier integration, Site Operations for installation, Finance for inventory valuation',
    techDirection: 'RFID-based real-time tracking with IoT edge processing and cloud-based inventory optimization engine',
    innovationElement: 'Comprehensive RFID-based material tracking system designed for HK construction site conditions and material types',
    technicalRequirements: 'UHF RFID readers, passive RFID tags, Raspberry Pi edge gateways, MQTT, React dashboard, Node.js, PostgreSQL, Docker',
    currentStage: 'Idea / R&D',
    stageStartDate: '2025-12-01',
    stageEndDate: '2026-02-28',
    stageStatus: 'Planning',
    stageDescription: 'RFID technology evaluation and pilot site selection for proof of concept',
    requireIP: '待定',
    ipRegion: 'Hong Kong',
    remarks: 'Projected 12-month ROI. Significant waste reduction aligns with sustainability goals and HK Waste Blueprint.',
    businessProposalFile: '',
    otherDocFile: '',
    status: 'pending',
    aiAnalysis: null,
    createdAt: '2025-07-23T00:00:00.000Z',
    uid: 'system',
  },
];

async function seedData() {
  console.log('Starting seed...');

  const batch = db.batch();

  // Write 20 ideas
  for (const idea of demoIdeas) {
    const docRef = db.collection('ideas').doc(idea.id);
    batch.set(docRef, {
      ...idea,
      createdAt: Timestamp.fromDate(new Date(idea.createdAt)),
    });
  }

  await batch.commit();
  console.log(`✅ Successfully seeded ${demoIdeas.length} ideas to Firestore!`);

  process.exit(0);
}

seedData().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});